#server:
#  port: ${PORT:8889}

spring: 
  cloud:
    config:
      uri: https://localhost:8888 

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8010/eureka/
      
message: Consumer configuration server is alive! v3
