server: 
  port: ${PORT:${SERVER_PORT:0}}
  #${PORT:8890}

spring: 
  cloud:
    config:
      uri: https://localhost:8888 

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8010/eureka/
      
message: Producer configuration server is alive!

